package monitor

import (
	"reflect"
	"time"
)

const (
	// MaxProbeTimeout is the upper bound of a configurable probe timeout.
	// Hub requests that run a probe allow Config.ProbeTimeout instead.
	MaxProbeTimeout = 60 * time.Second
	// DefaultProbeTimeout applies to icmp, tcp and dns probes without a Timeout.
	DefaultProbeTimeout = 3 * time.Second
	// DefaultHTTPProbeTimeout applies to http probes without a Timeout.
	DefaultHTTPProbeTimeout = 10 * time.Second
)

// ProtocolPush identifies monitors whose checks are reported to the monitor
// rather than probed by it.
const ProtocolPush = "push"

type SyncAction uint8

const (
	// SyncActionReplace indicates a full sync where the provided configs should replace all existing monitors for the system.
	SyncActionReplace SyncAction = iota
	// SyncActionUpsert indicates an incremental sync where the provided config should be added or updated.
	SyncActionUpsert
	// SyncActionDelete indicates an incremental sync where the provided config should be removed.
	SyncActionDelete
)

// Config defines a network monitor task sent from hub to agent.
type Config struct {
	// ID is the stable network_monitors record ID generated by the hub.
	ID       string `cbor:"0,keyasint"`
	Target   string `cbor:"1,keyasint"`
	Protocol string `cbor:"2,keyasint"` // "icmp", "tcp", "http", "dns" or "push"
	Port     uint16 `cbor:"3,keyasint,omitempty"`
	Interval uint16 `cbor:"4,keyasint"` // seconds
	// Server is the DNS server to query (host or host:port, default port 53).
	// Only used when Protocol is "dns"; empty means use the system resolver.
	Server string `cbor:"5,keyasint,omitempty"`
	// Timeout is the probe timeout in seconds; 0 uses the protocol default.
	Timeout uint16 `cbor:"6,keyasint,omitempty"`
	// HTTP holds request and response options. Only used when Protocol is "http".
	HTTP *HTTPOptions `cbor:"7,keyasint,omitempty"`
	// RetryInterval is the probe interval in seconds while the latest check
	// fails; 0 keeps Interval.
	RetryInterval uint16 `cbor:"8,keyasint,omitempty"`
}

// Equal reports whether two configs describe the same monitor task.
// Use it instead of == so Config can hold slices, maps and pointers; HTTP
// options are compared by value.
func (c Config) Equal(other Config) bool {
	return reflect.DeepEqual(c, other)
}

// ProbeTimeout returns the effective timeout of a single probe.
func (c Config) ProbeTimeout() time.Duration {
	if c.Timeout > 0 {
		return min(time.Duration(c.Timeout)*time.Second, MaxProbeTimeout)
	}
	if c.Protocol == "http" {
		return DefaultHTTPProbeTimeout
	}
	return DefaultProbeTimeout
}

// Legacy returns a copy without fields that agents older than
// beszel.MinVersionMonitorChecks do not support.
func (c Config) Legacy() Config {
	c.Timeout = 0
	c.HTTP = nil
	c.RetryInterval = 0
	return c
}

// CheckEvent is the outcome of a single probe.
//
// Within a batch, Err is omitted when it repeats the previous event's error,
// so a failed event without Err has the same error as the event before it.
// ExpandCheckErrors restores the omitted errors.
type CheckEvent struct {
	// At is the probe completion Unix timestamp in milliseconds.
	At int64 `cbor:"0,keyasint" json:"at"`
	// ResponseUs is the response time in microseconds, or -1 on failure.
	ResponseUs int64  `cbor:"1,keyasint" json:"res"`
	StatusCode uint16 `cbor:"2,keyasint,omitempty" json:"status,omitempty"`
	Err        string `cbor:"3,keyasint,omitempty" json:"err,omitempty"`
}

// Failed reports whether the check failed.
func (e CheckEvent) Failed() bool {
	return e.ResponseUs < 0
}

// CompactCheckErrors omits errors that repeat the previous event's error.
func CompactCheckErrors(events []CheckEvent) {
	var previous string
	for i := range events {
		current := events[i].Err
		if current != "" && current == previous {
			events[i].Err = ""
		}
		previous = current
	}
}

// ExpandCheckErrors restores errors omitted by CompactCheckErrors.
func ExpandCheckErrors(events []CheckEvent) {
	for i := 1; i < len(events); i++ {
		if events[i].Failed() && events[i].Err == "" && events[i-1].Failed() {
			events[i].Err = events[i-1].Err
		}
	}
}

// CertInfo holds details of the leaf TLS certificate presented by a target.
type CertInfo struct {
	// Expires is the certificate's NotAfter Unix timestamp in milliseconds.
	Expires int64  `cbor:"0,keyasint" json:"expires"`
	Issuer  string `cbor:"1,keyasint,omitempty" json:"issuer,omitempty"`
}

// SyncRequest defines an incremental or full monitor sync request sent to the agent.
type SyncRequest struct {
	Action  SyncAction `cbor:"0,keyasint"`
	Config  Config     `cbor:"1,keyasint,omitempty"`
	Configs []Config   `cbor:"2,keyasint,omitempty"`
	RunNow  bool       `cbor:"3,keyasint,omitempty"`
}

// SyncResponse returns the immediate result for an upsert when requested.
type SyncResponse struct {
	Result Result `cbor:"0,keyasint,omitempty"`
}

// Result holds aggregated monitor results for a single target.
//
// 0: avg response in microseconds
//
// 1: 1h average response in microseconds
//
// 2: min response in microseconds
//
// 3: 1h min response in microseconds
//
// 4: max response in microseconds
//
// 5: 1h max response in microseconds
//
// 6: packet loss percentage (0-100)
//
// 7: 1h packet loss percentage (0-100)
type Result struct {
	AvgResponse   int64   `cbor:"0,keyasint,omitempty"`
	AvgResponse1h int64   `cbor:"1,keyasint,omitempty"`
	MinResponse   int64   `cbor:"2,keyasint,omitempty"`
	MinResponse1h int64   `cbor:"3,keyasint,omitempty"`
	MaxResponse   int64   `cbor:"4,keyasint,omitempty"`
	MaxResponse1h int64   `cbor:"5,keyasint,omitempty"`
	PacketLoss    float64 `cbor:"6,keyasint,omitempty"`
	PacketLoss1h  float64 `cbor:"7,keyasint,omitempty"`
	// LastProbeAt is the latest completed probe's Unix timestamp in milliseconds.
	LastProbeAt int64 `cbor:"8,keyasint"`
	// SampleCount includes all completed probes since this monitor started.
	// Used for alert warm-up even when the interval is longer than 20 minutes.
	SampleCount int64 `cbor:"9,keyasint,omitempty"`
	// Counts and sum cover the current response window (or latest-sample
	// fallback), not the hourly window or lifetime SampleCount.
	TotalCount   int64 `cbor:"10,keyasint"`
	SuccessCount int64 `cbor:"11,keyasint"`
	ResponseSum  int64 `cbor:"12,keyasint"`
	// Cert is set for HTTPS targets when a certificate check has new info the hub has not stored yet.
	Cert *CertInfo `cbor:"13,keyasint,omitempty"`
	// Checks lists individual probe outcomes not yet reported, oldest first.
	// Only sent with default interval results and immediate probe results.
	Checks []CheckEvent `cbor:"14,keyasint,omitempty"`
	// Dropped counts unreported checks discarded because the queue was full.
	Dropped uint32 `cbor:"15,keyasint,omitempty"`
}

// IsZero reports whether the result is empty.
func (r Result) IsZero() bool {
	return reflect.ValueOf(r).IsZero()
}

// Stats holds response times in microseconds and packet loss percentage (0-100).
type Stats struct {
	ResAvg       float64 `json:"res_avg" db:"-"` // Derived for display; not stored.
	ResMin       float64 `json:"res_min" db:"res_min"`
	ResMax       float64 `json:"res_max" db:"res_max"`
	Loss         float64 `json:"loss" db:"-"` // Derived for display; not stored.
	TotalCount   int64   `json:"-" db:"total_count"`
	SuccessCount int64   `json:"-" db:"success_count"`
	ResponseSum  int64   `json:"-" db:"res_sum"`
}

func (s Stats) FromResult(result Result) Stats {
	return Stats{
		ResAvg:       float64(result.AvgResponse),
		ResMin:       float64(result.MinResponse),
		ResMax:       float64(result.MaxResponse),
		Loss:         result.PacketLoss,
		TotalCount:   result.TotalCount,
		SuccessCount: result.SuccessCount,
		ResponseSum:  result.ResponseSum,
	}
}
